### ISSUE TITLE
markdown 解析不出

### ISSUE THREAD

**Issue by smalltimoo** [DendiSe7enGitHub/Align#3]
有很多markdown语法解析不出
比如区块引用

**Comment by DendiSe7enGitHub** [comment]
blockquote 当时是因为我给H3 加了自定义样式 所以去掉了blockquote 的默认样式，你如果想要加上的话，可以在 src/asserts/docs.scss 里面加上 

```css
.post-content
blockquote::before {
      content: '\201C';
      color: #ed87bd5e;
      font-size: 2rem;
    }
    blockquote {
      display: flex;
      padding: 1%;
      margin: 2% auto;
      font-size: 1rem;
      background: #fff;
      max-width: 960px;
      letter-spacing: 0.3px;
      font-family: 'Roboto Slab';
      box-shadow: 20px 0px 20px 0px rgba(0, 0, 0, 0.2);
      color: rgba(18, 87, 134, 0.8);
      border-left: 5px solid #ed87bd5e;
      border-right: 5px solid #ed87bd5e;
      text-align: left;
      quotes: ' ' ' ';
    }
```

我也会把当前的源码更新一下 新增了很多变动没有同步过来。

顺便问一句，还有发现其他的标签没有样式吗？

**Comment by DendiSe7enGitHub** [comment]
> 有很多markdown语法解析不出
> 比如区块引用

blockquote 当时是因为我给H3 加了自定义样式 所以去掉了blockquote 的默认样式，你如果想要加上的话，可以在 src/asserts/docs.scss 里面加上

```css
.post-content
blockquote::before {
      content: '\201C';
      color: #ed87bd5e;
      font-size: 2rem;
    }
    blockquote {
      display: flex;
      padding: 1%;
      margin: 2% auto;
      font-size: 1rem;
      background: #fff;
      max-width: 960px;
      letter-spacing: 0.3px;
      font-family: 'Roboto Slab';
      box-shadow: 20px 0px 20px 0px rgba(0, 0, 0, 0.2);
      color: rgba(18, 87, 134, 0.8);
      border-left: 5px solid #ed87bd5e;
      border-right: 5px solid #ed87bd5e;
      text-align: left;
      quotes: ' ' ' ';
    }
```
我也会把当前的源码更新一下 新增了很多变动没有同步过来。

顺便问一句，还有发现其他的标签没有样式吗？
